#apps/sechic/extra_data/supplier_cost.py
suppliers_data = [
            ('1', 'GANT', 1.65),
            ('2', 'HUGO BOSS', 2.73),
            ('3', 'VANDOMA- António M. Sousa', 4.0),
            ('4', 'ESCORPION', 2.6),
            ('5', 'MAXMARA', 2.6),
            ('6', 'MARELLA', 2.7),
            ('7', 'PAUL & SHARK- DAMA', 2.5),
            ('8', 'MARCOTEX', 2.7),
            ('9', 'FLORENTINO COLECCION', 2.6),
            ('10', 'MEYER- HOSEN', 2.7),
            ('11', 'DECENIO', 2.5),
            ('12', 'MIGUEL BELLIDO', 3.0),
            ('13', 'LINDENMANN', 3.0),
            ('15', 'TOMMY HILFIGER', 2.45),
            ('17', 'LEBEK FASHION', 3.0),
            ('18', 'NAULOVER', 2.6),
            ('20', 'DIELMAR', 2.6),
            ('22', 'RALPH LAUREN', 2.7),
            ('23', 'LVX', 2.5),
            ('24', 'LIU.JO', 2.6),
            ('24', 'LIUJO', 2.6),
            ('25', 'PENNYBLACK', 2.6),
            ('26', 'CB BENNETT', 3.0),
            ('27', 'TOMMY HILFIGER- ACESS', 2.5),
            ('28', 'REFIVE', 2.5),
            ('29', 'MICHAELA LOUISA', 2.5),
            ('30', 'COCCINELLE', 2.61),
            ('31', 'LOVE MOSCHINO- SINV', 2.6),
            ('32', 'BOUTIQUE MOSCHINO-AEFFE', 2.6),
            ('33', 'TWINSET- ANDRÉ COSTA', 2.5),
            ('35', 'MORPHOPOLIS OFICINA DE ARQUITECTURA', 2.5),
            ('36', 'PINKO-CRIS CONF S.p.A', 2.5),
            ('37', 'GOLDEN SEASON', 2.5)
        ]
        