version: '3.8'

services:
  web-aitigos-django:
    container_name: aitigos
    restart: always
    build: .
    env_file:
      - .env.local
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - '5005:5005'
    command: ['gunicorn', '--config', 'gunicorn-cfg.py', 'config.wsgi']
    networks:
      - aitigos_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis_aitigos
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - aitigos_network
      
volumes:
  static_volume:
  media_volume:

networks:
  aitigos_network:
    driver: bridge
