# Generated by Django 5.0.6 on 2025-05-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('shopify_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('handle', models.CharField(blank=True, max_length=255, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopify Product',
                'verbose_name_plural': 'Shopify Products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyImage',
            fields=[
                ('image_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=1)),
                ('src', models.URLField(max_length=1000)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_shopify.shopifyproduct')),
            ],
            options={
                'verbose_name': 'Shopify Image',
                'verbose_name_plural': 'Shopify Images',
            },
        ),
        migrations.CreateModel(
            name='ShopifyVariant',
            fields=[
                ('variant_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position', models.IntegerField(default=1)),
                ('option1', models.CharField(blank=True, max_length=255, null=True)),
                ('option2', models.CharField(blank=True, max_length=255, null=True)),
                ('option3', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_shopify.shopifyproduct')),
            ],
            options={
                'verbose_name': 'Shopify Variant',
                'verbose_name_plural': 'Shopify Variants',
            },
        ),
    ]
