# Generated by Django 5.0.6 on 2025-05-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_shopify', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopifyImage',
        ),
    ]
