# Generated by Django 5.0.6 on 2025-05-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_shopify', '0001_initial'),
    ]

    operations = [
    ]
