# Generated by Django 5.0.6 on 2025-05-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_shopify', '0002_auto_20250505_1059'),
        ('product_shopify', '0002_delete_shopifyimage'),
    ]

    operations = [
    ]
