# Generated by Django 5.0.6 on 2025-05-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_shopify', '0003_merge_20250505_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyImage',
            fields=[
                ('image_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=1)),
                ('src', models.URLField(max_length=2000)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_shopify.shopifyproduct')),
            ],
            options={
                'verbose_name': 'Shopify Image',
                'verbose_name_plural': 'Shopify Images',
                'ordering': ['product', 'position'],
            },
        ),
    ]
