# Generated by Django 5.0.6 on 2025-05-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_shopify', '0004_shopifyimage'),
        ('shopify', '0004_shopify_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopify.shopify'),
        ),
    ]
