# Generated by Django 5.0.6 on 2025-05-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_shopify', '0005_shopifyproduct_store'),
        ('shopify', '0004_shopify_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopify.shopify'),
        ),
    ]
