# Generated by Django 5.0.6 on 2025-04-22 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopify',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loja Shopify', 'verbose_name_plural': 'Lojas Shopify'},
        ),
        migrations.AddField(
            model_name='shopify',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se a loja está ativa'),
        ),
        migrations.AddField(
            model_name='shopify',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='shopify',
            name='access_token',
            field=models.CharField(help_text='Token de acesso à API do Shopify', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopify',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro'),
        ),
        migrations.AlterField(
            model_name='shopify',
            name='email',
            field=models.EmailField(blank=True, help_text='Email associado à conta Shopify', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shopify',
            name='name',
            field=models.CharField(blank=True, help_text='Nome da loja', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopify',
            name='shop_domain',
            field=models.CharField(help_text='Domínio da loja Shopify (exemplo: loja.myshopify.com)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shopify',
            name='user',
            field=models.ForeignKey(help_text='Usuário proprietário desta loja', on_delete=django.db.models.deletion.CASCADE, related_name='shopify_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
