# Generated by Django 5.0.6 on 2025-05-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_alter_shopify_options_shopify_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopify',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shopify',
            name='user',
        ),
    ]
