# Generated by Django 5.0.6 on 2025-05-07 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_remove_shopify_name_remove_shopify_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopify',
            name='users',
            field=models.ManyToManyField(related_name='shopify_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
