# Generated by Django 5.0.6 on 2025-05-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sechic', '0002_remove_supplier_markup_suppliermarkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermarkup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
