# Generated by Django 5.0.6 on 2025-04-22 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moloni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('vat', models.CharField(blank=True, max_length=50, null=True)),
                ('url_image', models.URLField(blank=True, max_length=500, null=True)),
                ('moloni_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('moloni_refresh_token', models.CharField(blank=True, max_length=100, null=True)),
                ('users', models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
