# Generated by Django 5.0.6 on 2025-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moloni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moloni',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moloni',
            name='token_last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
