# Generated by Django 5.0.6 on 2025-05-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moloni', '0003_molonicredentials'),
        ('product_moloni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moloni.moloni'),
        ),
    ]
