# Generated by Django 5.0.6 on 2025-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_moloni', '0002_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
